# Generated by Django 5.1.7 on 2025-03-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='products',
            new_name='product',
        ),
    ]
